language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: kt+/gJWeYZiitHFSgaVcdComEQmFXXDBxhugbLqr1gfjeXrk7xkbUu8pX65LqAlcMyk3SNI39iO7zhU8LQOIT822UfmfoN6aOiGm2K1LAfW+iG0ZZMG0d9WmZ6Q4YSNh2FvNWw/P1OC5J+A0wVw8fpno88vTLD3tbHdfKB26hOt/MJm47cxycI2GU1kh9HjeQzwS0n+CRYr1cf5qOkq9GgXegon+4WgVfOKNW1rHXaN+6Yx4MMLWubLgKCuhGzmfjqQz4uD/Wdp1P+lyjn7EunpheIXUiwcIPCU4ypgNdIy4udogJvx4AttMUK1wL29I4flvD8w3OjIDcwj8W3Nofz+q+ag4cCrM71dgrIgs3+tPnpXv74esc8VVo0CLK8JOFcyuhS4lMz7J4O0r1LKbH9g40HYumjwvYvbGw8TDbzxj3Q7BDpu6ITBmTmpM31OYgQZDi2jASnPZSTCjqz4VxRAAhZ46e5DBNWdO18ky/ubWTHU33l+3EJEFqdd3jCACYEkyDFhvfy+jxEtgcOY/kKyCM8v7CxxGvDv5DT7G4m4Mbch0Ts0sLITuTWkFTb9mX6mxRbsAwsZ67oP/1mOnMrVA9UL2vDnkPlPChT4fehzeJpo+dDRG5eAtBbaJM/d6KTIVEgJqt6ETNlT3P00evi3Rh56k6uw6lC7/nhnZ6rM=
  - secure: hUbwPIfIb2CU6E/SxSv6EZ8fS4Wzr16fJSl6wkDPH07P6qHd7ndW5dVhz2eYrOOCUSSxwe1dR6d7RQIRK3vv0TV517RHMInKhEBtGLvu+zWnA9NjfDKK7pkLQ/n7l9lq3dn4RNxZ5kDJ02CNa29cQ92eHuOQLc8HrthkyD38sSioCljCNOOm4Te0uj5MpzRkriPbVCerqpCrJZ9rFQlCDdR9ovU2Du12rATc4bVMj3syVkcBRhKciB2wJzUTF64LYzQBuzAbH2zJpwezF8mvSSPVl9kKgGdN4B2v8+JQbw8qEWRG9fu12jDxeRGDIHQiutaUXuerWdVyPhCW2QccQTKxAcTq5bv0nG+JMgoeDbEloEB7L7HelD5UmoKY6BcfyT4cxNU0R9D6QyoCLOGH4H76J7plkxEr+IfSmqJYd+sKvcBWWD3cuEwXhjTi437nrh+zkvVG4WWkRRqlOt8X7w5Zh83CCXkzQtDFyqVqTIP+SRAmyg8kPUGLeYBjYUuxemd992DW7KxmptT3V+/4mD2QO9owkdL+l27Rsv82LNZtOj17J+arWx4UcDik6w0FyaDAK9/adwxkwKI0tpuAAxVmA8/p4tPN4u0ImId5xz0XNeaztbY7fVPWUKUyySaCbqbZ0bzHWNuKn9jngGhdfFi5GrNPT47gPOoMiSHXlX0=
